site_name: UGRID
site_url: http://ugrid-conventions.github.io/ugrid-conventions
site_description: UGRID Conventions
site_author: UGRID Team

repo_url: https://github.com/ugrid-conventions/ugrid-conventions

pages:
  - Home: index.md
  - subsetting: ugrid-subsetting.md
  - conformance: conformance.md

markdown_extensions:
  - extra
  - smarty
  - markdown_checklist.extension
  - toc:
      permalink: ""
  - mdx_gh_links:
      user: ugrid-conventions
      repo: ugrid-conventions

theme: readthedocs
docs_dir: src
site_dir: _site
google_analytics: ['UA-9133259-16', 'UGRID.github.io']

plugins:
    - search
